/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa_Presentacion;

import Capa_Negocio.DataArticulo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jefer
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        ListarArticulos();
    }

    public void ListarArticulos() {
        DefaultTableModel tabla = new DefaultTableModel();
        DataArticulo objart = new DataArticulo();
        ArrayList<DataArticulo> lista2 = new ArrayList();
        lista2 = objart.ListaArticulos();
        tabla.addColumn("Codigo");
        tabla.addColumn("Nombre");
        tabla.addColumn("Precio");
        tabla.setRowCount(lista2.size());
        int i = 0;
        for (DataArticulo x : lista2) {
            tabla.setValueAt(x.getArt_cod(), i, 0);
            tabla.setValueAt(x.getArt_nom(), i, 1);
            tabla.setValueAt(x.getArt_pre(), i, 2);
            i++;
        }
        this.jTableHistorial.setModel(tabla);
    }

    public void LimpiarCajasTexto() {
        this.JtfCodigo.setText("");
        this.JtfNombre.setText("");
        this.JtfPrecio.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableHistorial = new javax.swing.JTable();
        JBtPagar = new javax.swing.JButton();
        JBtFacturar = new javax.swing.JButton();
        JBtEliminar = new javax.swing.JButton();
        JtfFactura = new javax.swing.JTextField();
        JBtSalir = new javax.swing.JButton();
        JlbListProduct = new javax.swing.JLabel();
        JlbFactura = new javax.swing.JLabel();
        JtfCodigo = new javax.swing.JTextField();
        JtfNombre = new javax.swing.JTextField();
        JtfPrecio = new javax.swing.JTextField();
        JlbCodigo = new javax.swing.JLabel();
        JlbNombre = new javax.swing.JLabel();
        JlbPrecio = new javax.swing.JLabel();
        JBtEditar = new javax.swing.JButton();
        JlbHisPedidos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePedido = new javax.swing.JTable();
        JlbPedido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableList);

        jTableHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableHistorial);

        JBtPagar.setText("Pagar");

        JBtFacturar.setText("Facturar");
        JBtFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtFacturarActionPerformed(evt);
            }
        });

        JBtEliminar.setText("Eliminar");
        JBtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtEliminarActionPerformed(evt);
            }
        });

        JtfFactura.setText("facturona");

        JBtSalir.setText("Salir");
        JBtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtSalirActionPerformed(evt);
            }
        });

        JlbListProduct.setText("LISTA PRODUCTOS");

        JlbFactura.setText("FACTURA");

        JlbCodigo.setText("Código:");

        JlbNombre.setText("Coctel:");

        JlbPrecio.setText("Precio:");

        JBtEditar.setText("Editar");
        JBtEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtEditarActionPerformed(evt);
            }
        });

        JlbHisPedidos.setText("HISTORIAL PEDIDOS");

        jTablePedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTablePedido);

        JlbPedido.setText("PEDIDO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(JlbPedido)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtEliminar)
                            .addComponent(JBtSalir)
                            .addComponent(JBtPagar)
                            .addComponent(JBtFacturar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JlbListProduct)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlbCodigo)
                                    .addComponent(JlbNombre)
                                    .addComponent(JlbPrecio))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JtfCodigo)
                                    .addComponent(JtfNombre)
                                    .addComponent(JtfPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBtEditar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JtfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JlbFactura)
                        .addGap(189, 189, 189))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JlbHisPedidos)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(JBtEditar)
                        .addGap(83, 83, 83)
                        .addComponent(JlbFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtEliminar)
                            .addComponent(JtfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBtPagar)
                                .addGap(117, 117, 117)
                                .addComponent(JBtFacturar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBtSalir)
                                .addGap(190, 190, 190))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JlbHisPedidos)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlbCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlbNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlbPrecio))
                        .addGap(34, 34, 34)
                        .addComponent(JlbListProduct)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(JlbPedido)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtSalirActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(null, "Esta Seguro?");
        if (r == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_JBtSalirActionPerformed

    private void JBtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtEliminarActionPerformed
        // TODO add your handling code here:
        int Res = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el articulo: " + this.JtfCodigo.getText());
        if (Res == 0) {
            DataArticulo objart = new DataArticulo();
            objart.setArt_cod(this.JtfCodigo.getText());
            JOptionPane.showMessageDialog(null, objart.EliminaArticulo());
            ListarArticulos();
            JOptionPane.showMessageDialog(null, "Articulo Eliminado");
        }
    }//GEN-LAST:event_JBtEliminarActionPerformed

    private void JBtFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtFacturarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel pedidoTableModel = (DefaultTableModel) jTablePedido.getModel();
        int rowCount = pedidoTableModel.getRowCount();

        StringBuilder facturaText = new StringBuilder();
        facturaText.append("FACTURA:\n");

        for (int i = 0; i < rowCount; i++) {
            String codigo = pedidoTableModel.getValueAt(i, 0).toString();
            String nombre = pedidoTableModel.getValueAt(i, 1).toString();
            String precio = pedidoTableModel.getValueAt(i, 2).toString();

            facturaText.append("Producto ").append(i + 1).append(": ")
                    .append("Código: ").append(codigo)
                    .append(", Nombre: ").append(nombre)
                    .append(", Precio: ").append(precio).append("\n");
        }

        JtfFactura.setText(facturaText.toString());
    }//GEN-LAST:event_JBtFacturarActionPerformed

    private void JBtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtEditarActionPerformed
        // TODO add your handling code here:
        DataArticulo objart = new DataArticulo();
        objart.setArt_cod(this.JtfCodigo.getText());
        objart.setArt_nom(this.JtfNombre.getText());
        objart.setArt_pre(Double.parseDouble(this.JtfPrecio.getText()));
        JOptionPane.showMessageDialog(null, objart.EditarArticulo());
        ListarArticulos();
    }//GEN-LAST:event_JBtEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtEditar;
    private javax.swing.JButton JBtEliminar;
    private javax.swing.JButton JBtFacturar;
    private javax.swing.JButton JBtPagar;
    private javax.swing.JButton JBtSalir;
    private javax.swing.JLabel JlbCodigo;
    private javax.swing.JLabel JlbFactura;
    private javax.swing.JLabel JlbHisPedidos;
    private javax.swing.JLabel JlbListProduct;
    private javax.swing.JLabel JlbNombre;
    private javax.swing.JLabel JlbPedido;
    private javax.swing.JLabel JlbPrecio;
    private javax.swing.JTextField JtfCodigo;
    private javax.swing.JTextField JtfFactura;
    private javax.swing.JTextField JtfNombre;
    private javax.swing.JTextField JtfPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableHistorial;
    private javax.swing.JTable jTableList;
    private javax.swing.JTable jTablePedido;
    // End of variables declaration//GEN-END:variables
}
